version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET ...
      - dotnet --version

  pre_build:
    commands:
      - echo Restoring dependencies...
      - cd API/StainManager.WebAPI
      - dotnet restore

  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Running tests...
      - dotnet test --no-build --verbosity normal

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'API/bin/Release/net9.0'

cache:
  paths:
    - '/root/.nuget/packages/**/*'
