version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 9.0
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0
      - dotnet --version
      - dotnet --list-runtimes

  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore ./API/StainManager.WebAPI/StainManager.WebAPI.csproj

  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Running tests...
      - dotnet test --no-build --verbosity normal

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'API/bin/Release/net9.0'

cache:
  paths:
    - '/root/.nuget/packages/**/*'
