version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0
      - dotnet --version
      - echo Installing dotnet-ef tool...
      - dotnet tool install --global dotnet-ef
      - export PATH="$PATH:/root/.dotnet/tools"

  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore ./API/StainManager.WebAPI/StainManager.WebAPI.csproj

  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Publishing the project...
      - dotnet publish --configuration Release --output ./publish
      - echo Checking if publish directory is not empty...
      - if [ -n "$(ls -A ./publish)" ]; then
          echo Creating zip file...;
          cd publish;
          zip -r ../StainManager.WebAPI.zip .;
          cd ..;
        else
          echo Publish directory is empty, skipping zip creation;
        fi
      - echo Creating EF Core migrations bundle...
      - dotnet ef migrations bundle --project API/StainManager.Infrastructure --startup-project API/StainManager.WebAPI --output ./efbundle
      - echo Creating zip file for EF Core migrations bundle...
      - zip -r efbundle.zip efbundle

artifacts:
  files:
    - StainManager.WebAPI.zip
    - efbundle.zip
  discard-paths: yes

cache:
  paths:
    - '/root/.nuget/packages/**/*'
