version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 9.0
    commands:
      # Install any dependencies needed
      - echo Installing dependencies...
  
  pre_build:
    commands:
      # Restore NuGet packages
      - echo Restoring NuGet packages...
      - dotnet restore
      
      # Run tests (optional)
      - echo Running tests...
      - dotnet test --no-restore
  
  build:
    commands:
      # Build the application
      - echo Building the application...
      - dotnet build --configuration Release --no-restore
      
      # Publish the application
      - echo Publishing the application...
      - dotnet publish --configuration Release --no-build --output ./publish

  post_build:
    commands:
      # Any post build steps, like creating deployment packages
      - echo Build completed on `date`
      # Create deployment artifacts zip
      - cd publish && zip -r ../deploy_package.zip *
      # Clear any previous artifacts
      - rm -rf ./publish

artifacts:
  files:
    - deploy_package.zip
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.nuget/packages/**/*'