version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET 9.0.200...
      # Download the dotnet-install script
      - wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      - chmod +x dotnet-install.sh
      # Install .NET 9.0.200
      - ./dotnet-install.sh --version 9.0.200 --install-dir /usr/share/dotnet
      # Add dotnet to PATH
      - export PATH="/usr/share/dotnet:$PATH"
      - dotnet --info
  
  pre_build:
    commands:
      # Navigate to the API directory
      - cd API
      # Restore NuGet packages for the WebAPI project
      - echo Restoring NuGet packages...
      - dotnet restore StainManager.WebAPI/StainManager.WebAPI.csproj
      
      # Run tests if you have them (adjust the path as needed)
      # - echo Running tests...
      # - dotnet test StainManager.Tests/StainManager.Tests.csproj --no-restore
  
  build:
    commands:
      # Build only the WebAPI project (which will build dependencies)
      - echo Building the WebAPI application...
      - dotnet build StainManager.WebAPI/StainManager.WebAPI.csproj --configuration Release --no-restore
      
      # Publish only the WebAPI project
      - echo Publishing the WebAPI application...
      - dotnet publish StainManager.WebAPI/StainManager.WebAPI.csproj --configuration Release --no-build --output ../publish

  post_build:
    commands:
      # Any post build steps
      - echo Build completed on `date`
      # Create deployment artifacts zip from the publish directory
      - cd ../publish && zip -r ../deploy_package.zip *
      # Clean up
      - cd .. && rm -rf ./publish

artifacts:
  files:
    - deploy_package.zip
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.nuget/packages/**/*'