name: Build and Deploy to Elastic Beanstalk (Dev)

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:
    # Manual trigger for development branch
    inputs:
      deploy:
        description: 'Deploy to Elastic Beanstalk'
        required: true
        default: true
        type: boolean

env:
  DOTNET_VERSION: '9.0.200'
  SOLUTION_PATH: 'API/StainManager.WebAPI/StainManager.WebAPI.csproj'
  ARTIFACT_NAME: 'stainmanager-webapi-dev'
  EB_APPLICATION_NAME: 'StainManager'
  EB_ENVIRONMENT_NAME: 'StainManager-dev'
  AWS_REGION: 'us-east-2'
  # Update the region as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Verify .NET installation
        run: dotnet --info
      
      - name: Install EF Core tools
        run: |
          dotnet new tool-manifest --force
          dotnet tool install --local dotnet-ef
          dotnet tool restore
          
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: |
          # Find and run all test projects
          for testProject in $(find . -name "*.Tests.csproj" -o -name "*Tests.csproj"); do
            echo "Running tests for: $testProject"
            dotnet test $testProject --configuration Release --no-build --verbosity normal
          done

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --output ./publish --no-build

      - name: Generate deployment package
        run: |
          cd publish
          zip -r deploy.zip ./*
          cd ..
          mv publish/deploy.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy.zip
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./deploy-package/

      - name: Prepare Elastic Beanstalk Configuration
        run: |
          mkdir -p ./deploy-package/.ebextensions
          cp API/StainManager.WebAPI/.ebextensions/dev/config.yml ./deploy-package/.ebextensions/config.yml
          
          # Replace placeholder with actual environment variable reference
          sed -i 's/${DEV_CONN_STRING}/${{ secrets.DEV_DB_CONNECTION_STRING }}/g' ./deploy-package/.ebextensions/config.yml
          
          # Re-zip the deployment package with configuration
          cd ./deploy-package
          unzip -q deploy.zip -d ./contents
          cp -r .ebextensions ./contents/
          cd ./contents
          zip -r ../updated-deploy.zip *
          cd ..
          mv updated-deploy.zip ../deploy.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: dev-${{ github.run_number }}-${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
          wait_for_deployment: true
          wait_for_environment_recovery: 300

      - name: Setup .NET for migrations
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Get GitHub Actions IP
        id: github-ip
        run: |
          # Get the current runner's outbound IP
          GITHUB_RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "ip=$GITHUB_RUNNER_IP" >> $GITHUB_OUTPUT
          echo "GitHub Actions runner IP: $GITHUB_RUNNER_IP"

      - name: Update RDS Security Group
        run: |
          # Get the runner's IP address
          GITHUB_RUNNER_IP="${{ steps.github-ip.outputs.ip }}"

          # Define the security group ID for your RDS instance
          SECURITY_GROUP_ID="sg-0aa037a4d46015754"

          # Add an inbound rule to the security group for the current runner's IP
          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 1433 \
            --cidr "$GITHUB_RUNNER_IP/32"

          echo "Added $GITHUB_RUNNER_IP to RDS security group $SECURITY_GROUP_ID"

      - name: Apply database migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DEV_DB_CONNECTION_STRING }}
        run: |
          # Install EF Core tools locally to avoid conflicts with global.json
          dotnet new tool-manifest --force
          dotnet tool install --local dotnet-ef
          dotnet tool restore
          
          # Navigate to the right project directory
          cd API/StainManager.Infrastructure
          
          # Apply migrations using the local tool with explicit connection string
          dotnet ef database update --startup-project ../StainManager.WebAPI
          
          # Verify migration success
          if [ $? -eq 0 ]; then
            echo "Database migrations applied successfully"
          else
            echo "Database migration failed"
            exit 1
          fi

      - name: Remove temporary security group rule
        if: always() # Run this step even if previous steps fail
        run: |
          GITHUB_RUNNER_IP="${{ steps.github-ip.outputs.ip }}"
          SECURITY_GROUP_ID="sg-0aa037a4d46015754" # Same as above
      
          aws ec2 revoke-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 1433 \
            --cidr "$GITHUB_RUNNER_IP/32"
      
          echo "Removed temporary access for $GITHUB_RUNNER_IP from security group"